### ISSUE TITLE
JS comment syntax used for sourceMappingURL in CSS files if loadMaps: true

### ISSUE THREAD

**Issue by benjclark** [gulp-sourcemaps/gulp-sourcemaps#363]
### Expected behaviour (css file output at end of build process)
```css
.u-text-xxs{font-size:1rem}.u-text-xs{font-size:1.2rem}.u-text-sm{font-size:1.4rem}.u-text-md{font-size:1.7rem}.u-text-lg{font-size:2.1rem}
/*# sourceMappingURL=main-823e348857.css.map */
```

### Actual behaviour (css file output at end of build process)
```css
.u-text-xxs{font-size:1rem}.u-text-xs{font-size:1.2rem}.u-text-sm{font-size:1.4rem}.u-text-md{font-size:1.7rem}.u-text-lg{font-size:2.1rem}

//# sourceMappingURL=main-823e348857.css.map
```

### Associated build process
```js
const gulp = require('gulp');
const rev = require('gulp-rev');
const sass = require('gulp-sass');
const sourcemaps = require('gulp-sourcemaps');

const folder = {
    src: 'src/main/web',
    dist: 'public'
};

gulp.task('styles', () => {
    return gulp
        .src(`${folder.src}/styles/**/*.scss`, {base: folder.src})
        .pipe(sourcemaps.init())
        .pipe(sass({
            outputStyle: 'expanded',
            includePaths: ['./node_modules/include-media/dist/']
        }))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(folder.dist));
});

gulp.task('rev-assets', () => {
    return gulp
        .src(`${folder.dist}/styles/**/*.css`, {base: folder.dist})
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(rev())
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(folder.dist));
});

// > gulp styles && gulp rev-assets
```

### package.json devDependencies
```json
"devDependencies": {
  "gulp": "^3.9.1",
  "gulp-rev": "^7.1.2",
  "gulp-sass": "^3.1.0",
  "gulp-sourcemaps": "^2.4.1"
}
```

Also of note:
If I remove `loadMaps: true` then this is the output:

```css
.u-text-xxs{font-size:1rem}.u-text-xs{font-size:1.2rem}.u-text-sm{font-size:1.4rem}.u-text-md{font-size:1.7rem}.u-text-lg{font-size:2.1rem}
/*# sourceMappingURL=main.css.map */

/*# sourceMappingURL=main-823e348857.css.map */
```
